# TODO: Translation updated at 2020-09-18 00:45

translate spanish strings:

    # game/options.rpy:15
    old "Born To Chase Owls"
    new "Nacido para Perseguir Búhos"

    # game/options.rpy:32
    old "Once Wren finally was able to get into the swing of things at college people make it hard for him, again. After leaving class, he meets one of his exes. They talk and reconnect after several years. Then, thinking things will be fine he meets a new guy that instantly is interested in Wren. The two guys ,Somchai and Dominic, battle for Wren’s love. When Wren finally chooses one of the guys, problems of being with either of them start to arise. Will Wren make the right choices and maintain the relationship of his dreams?\n\n{b}ChasingOwls Production Team:{/b}\n\nAnthony Osgood... Director/ Coding\n\nKarla Olaguez... Story\n\nBrenna Kreps... Sprites/ CG's\n\nJennyfer Calderon... Backgrounds\n\nRaven Simon... Music/ Audio\n\n{b}Translators:{/b}\n\nUriel Valentin Nieto... Spanish\n\n"
    new "Una vez que Wren finalmente pudo entrar en el ritmo de las cosas en la universidad, la gente se lo puso difícil, nuevamente. Después de salir de clase, conoce a uno de sus ex. Hablan y se vuelven a conectar después de varios años. Entonces, pensando que todo irá bien, conoce a un chico nuevo que instantáneamente se interesa en Wren. Los dos chicos, Somchai y Dominic, luchan por el amor de Wren. Cuando Wren finalmente elige a uno de los chicos, comienzan a surgir problemas de estar con cualquiera de ellos. ¿Wren tomará las decisiones correctas y mantendrá la relación de sus sueños? \ N \ n {b} Equipo de producción de ChasingOwls: {/ b} \ n \ nAnthony Osgood ... Director / Coding \ n \ nKarla Olaguez ... Script ( Días 1-2) \ n \ nTaylor Marshall ... Guión (Días 4 ~) \ n \ nBrenna Kreps ... Sprites / CG's \ n \ nJennyfer Calderon ... Fondos \ n \ nRaven Simon ... Música / Audio \ n \ n {b} Escritores fantasmas: {/ b} \ n \ nAnthony Osgood ... Día 3 \ n \ n {b} Traductores: {/ b} \ n \ nUriel Valentin Nieto ... Español \ n \n"
# TODO: Translation updated at 2021-04-30 14:54

translate spanish strings:

    # game/options.rpy:32
    old "Once Wren finally was able to get into the swing of things at college people make it hard for him, again. After leaving class, he meets one of his exes. They talk and reconnect after several years. Then, thinking things will be fine he meets a new guy that instantly is interested in Wren. The two guys ,Somchai and Dominic, battle for Wren’s love. When Wren finally chooses one of the guys, problems of being with either of them start to arise. Will Wren make the right choices and maintain the relationship of his dreams?\n\n{b}ChasingOwls Production Team:{/b}\n\nAnthony Osgood... Director/ Coding\n\nKarla Olaguez... Script (Days 1-2)\n\nTaylor Marshall... Script (Days 4~)\n\nBrenna Kreps... Sprites/ CG's\n\nJennyfer Calderon... Backgrounds\n\nRaven Simon... Music/ Audio\n\n{b}Ghost Writers:{/b}\n\nAnthony Osgood... Day 3\n\n{b}Translators:{/b}\n\nUriel Valentin Nieto... Spanish\n\n"
    new "Una vez que Wren finalmente pudo entrar en el ritmo de las cosas en la universidad, la gente se lo puso difícil, nuevamente. Después de salir de clase, conoce a uno de sus ex. Hablan y se vuelven a conectar después de varios años. Entonces, pensando que todo irá bien, conoce a un chico nuevo que instantáneamente se interesa en Wren. Los dos chicos, Somchai y Dominic, luchan por el amor de Wren. Cuando Wren finalmente elige a uno de los chicos, comienzan a surgir problemas de estar con cualquiera de ellos. ¿Wren tomará las decisiones correctas y mantendrá la relación de sus sueños? \n\n{b}Equipo de producción de ChasingOwls:{/b}\n\nAnthony Osgood... Director/ Coding\n\nKarla Olaguez... Script (Días 1-2)\n\nTaylor Marshall... Guión (Días 4~)\n\nBrenna Kreps... Sprites / CG's\n\nJennyfer Calderon... Fondos\n\nRaven Simon... Música / Audio\n\n{b}Escritores fantasmas:{/b}\n\nAnthony Osgood... Día 3\n\n{b}Traductores:{/b}\n\nUriel Valentin Nieto... Español\n\n"
